using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Nodes;
namespace AgentSupervisor.Infrastructure;

public sealed class ClaudeSettingsHookMerger
{
    public const int PermissionRequestTimeoutSeconds = 1800; private readonly string _path; private readonly string _command; private readonly string _matchSuffix;
    public ClaudeSettingsHookMerger(string path, string? runtimeId = null, string? executablePath = null) { _path = path; var exe = executablePath ?? Process.GetCurrentProcess().MainModule?.FileName ?? "AgentSupervisor.App.exe"; var runtime = runtimeId ?? "windows"; _command = $"\"{exe}\" hook-forward --runtime {runtime}"; _matchSuffix = $"hook-forward --runtime {runtime}"; }
    public string Merge(string url, string? token, bool dryRun = false) { var r = File.Exists(_path) ? JsonNode.Parse(File.ReadAllText(_path))?.AsObject() ?? new() : new(); var h = r["hooks"] as JsonObject ?? new(); r["hooks"] = h; Add(h, "Notification", null, 5); Add(h, "Stop", null, 5); Add(h, "SessionStart", null, 5); Add(h, "SessionEnd", null, 5); Add(h, "PermissionRequest", null, PermissionRequestTimeoutSeconds); Add(h, "PreToolUse", "AskUserQuestion", 5); var o = r.ToJsonString(new JsonSerializerOptions { WriteIndented = true }); if (!dryRun) { if (File.Exists(_path)) File.Copy(_path, _path + "." + DateTimeOffset.UtcNow.ToString("yyyyMMddHHmmssfff") + ".bak"); Directory.CreateDirectory(Path.GetDirectoryName(_path)!); File.WriteAllText(_path, o); } return o; }
    private bool IsOurCommand(string? command) => command is not null && command.EndsWith(_matchSuffix, StringComparison.Ordinal);
    private void Add(JsonObject h, string name, string? matcher, int timeout) { var a = h[name] as JsonArray ?? new(); var existing = a.FirstOrDefault(x => x?["hooks"] is JsonArray i && i.Any(y => y?["type"]?.GetValue<string>() == "command" && IsOurCommand(y?["command"]?.GetValue<string>()))); if (existing is not null) { foreach (var y in (JsonArray)existing["hooks"]!) if (y?["type"]?.GetValue<string>() == "command" && IsOurCommand(y?["command"]?.GetValue<string>())) { y!["command"] = _command; y["timeout"] = timeout; } } else { var entry = new JsonObject(); if (matcher is not null) entry["matcher"] = matcher; entry["hooks"] = new JsonArray(new JsonObject { { "type", "command" }, { "command", _command }, { "timeout", timeout } }); a.Add(entry); } h[name] = a; }
    public void Uninstall(bool dryRun = false) { if (!File.Exists(_path)) return; var r = JsonNode.Parse(File.ReadAllText(_path))?.AsObject(); if (r?["hooks"] is JsonObject h) foreach (var n in new[] { "Notification", "Stop", "SessionStart", "SessionEnd", "PermissionRequest", "PreToolUse" }) if (h[n] is JsonArray a) { for (var i = a.Count - 1; i >= 0; i--) if (a[i]?["hooks"] is JsonArray inner && inner.Any(y => y?["type"]?.GetValue<string>() == "command" && IsOurCommand(y?["command"]?.GetValue<string>()))) a.RemoveAt(i); if (a.Count == 0) h.Remove(n); } if (dryRun) return; File.Copy(_path, _path + "." + DateTimeOffset.UtcNow.ToString("yyyyMMddHHmmssfff") + ".bak"); File.WriteAllText(_path, r?.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) ?? "{}"); }
}
